name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'

      - run: |
          cd my-first-book
          mdbook build

      - name: Create latest HTML redirect file
        run: |
          cd my-first-book
          mkdir ./latest
          cat > ./latest/index.html <<EOF
          <!DOCTYPE html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; URL=../666/">
          <link rel="canonical" href="../666/">
          EOF

      - name: Set latest to point to tag
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./latest/
          destination_dir: .my-first-book/latest/